### ISSUE TITLE
Add Project.toml/Manifest.toml in QGF

### ISSUE THREAD

**Issue by navidcy** [Ira-Shokar/Stochastic_Latent_Transformer#1]
It'd be nice if you included the toml files in the QGF directory so that whoever tries to reproduce the results uses the same versions of GeophysicalFlows.jl and/or FourierFlows.jl like the ones you used.

(Nice work btw! -- I'm very keen to read the arXiv paper in detail!)

**Comment by Ira-Shokar** [comment]
Thank you Navid - I have now included the necessary requirements files. Great work with GeophysicalFlows.jl and FourierFlows.jl, see below comparisons with the previous Matlab script I was using:

- MATLAB script (500 time units at dt=4e-2- **894 mins on CPU** at dt=4e-2 on Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz using 4 cores)
- GeophysicalFlows (500 time units at dt=4e-2- **282 mins on CPU** at dt=4e-2 on Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz using 4 cores)
- GeophysicalFlows (500 time units at dt=4e-2- **29 mins on GPU**  on Tesla P100-PCIE-16GB @ 2.30GHz using 896 cores)

**Comment by Ira-Shokar** [comment]
Thank you Navid - I have now included the necessary requirements files. Great work with GeophysicalFlows.jl and FourierFlows.jl, see below comparisons with the previous Matlab script I was using:

- MATLAB script (500 time units at dt=4e-2- **894 mins on CPU** on Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz using 4 cores)
- GeophysicalFlows.jl (500 time units at dt=4e-2- **282 mins on CPU** on Intel(R) Xeon(R) Gold 6140 CPU @ 2.30GHz using 4 cores)
- GeophysicalFlows.jl (500 time units at dt=4e-2- **29 mins on GPU** on Tesla P100-PCIE-16GB @ 2.30GHz using 896 cores)
